name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PYTHONDONTWRITEBYTECODE: "1"

jobs:
  lint:
    name: Ruff lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: constraints.txt

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          python -m pip install -c constraints.txt ruff

      - name: Lint
        run: ruff check .

  type-check:
    name: Mypy type check
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            constraints.txt
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -c constraints.txt ".[dev]"

      - name: Run mypy
        run: mypy btcmi

  smoke:
    name: Smoke tests
    runs-on: ubuntu-latest
    needs:
      - lint
      - type-check
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            constraints.txt
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -c constraints.txt ".[dev]"

      - name: Run smoke tests
        run: pytest -m smoke --maxfail=1 --disable-warnings

  regression:
    name: Regression suite
    runs-on: ubuntu-latest
    needs: smoke
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            constraints.txt
            pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -c constraints.txt ".[dev]"

      - name: Run end-to-end examples
        env:
          PYTHONPATH: .
        run: python examples/run_e2e.py

      - name: Run regression tests
        run: pytest --disable-warnings
